### ISSUE TITLE
Prikaz delavnic, arhiv ne dela

### ISSUE THREAD

**Issue by vidpugelj** [OLFS-Peskovnik/spletna_stran#6]
Arhiv ne dela. Delavnice, ki so objavljene v maju ne prilaže

**Comment by vidpugelj** [comment]
Prikazuje delavnice v maju. Napaka je bila v datumu. Spremenil iz 2023-05-8 -> 2023-05-08.
Arhiv še zmeraj ni konfiguriran.

**Comment by Jure-D** [comment]
Problem je v tem, da trenutno ni dodanih nobenih obvestil, posledično arhiv nima kaj za prikazat.
