### ISSUE TITLE
Urnik

### ISSUE THREAD

**Issue by vidpugelj** [OLFS-Peskovnik/spletna_stran#7]
Živijo,
bi lahko dodal urnik na spletno stran?

Nekaj v tem smislu:
![slika](https://github.com/OLFS-Peskovnik/spletna_stran/assets/22709304/12e10ab1-de62-4c05-b1fa-e02cf8642119)

Urnik: 
Pripravniki: pon., sre. : 14:00 - 16:00
Člani: pon.-pet.: 10:00 - 18:00
Višji člani: pon.-sob.: 6:00 - 20:00

**Comment by Jure-D** [comment]
Urejeno!
